### ISSUE TITLE
Don't save file utf-8 char set on local folder with DonwloadSubtitles method 

### ISSUE THREAD

**Issue by ekucet** [vankasteelj/opensubtitles-api#38] opened 2018-08-22 21:27 UTC
```
const OS = require('opensubtitles-api');
const OpenSubtitles = new OS('Butter v1');

OpenSubtitles.api.LogIn('*****', '*****', '**', 'Butter v1').then(response => {
    console.log(response);
    OpenSubtitles.api.DownloadSubtitles(response.token, ['1955708358']).then(data => {
        console.log(data);
    }).catch(error => {
        console.log(error);
    });
}).catch(error => {
    console.log(error);
});
```

i want to data save to utf-8 char code. Are you using another framework for file download process? I have not found what I need to do here.

**Comment by vankasteelj** [comment] 2018-08-23 07:43
from: http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#DownloadSubtitles

> "array DownloadSubtitles( $token, array($IDSubtitleFile, $IDSubtitleFile,...) )"
>
> Returns BASE64 encoded gzipped IDSubtitleFile(s). You need to BASE64 decode and ungzip 'data' to get its contents.

You should be able to decode b64 then unzip using https://gist.github.com/vankasteelj/ceaf706881be02452ac2#file-gunzipbase64-js-L15

```
var data = 'xxx';                                 // base64 encoded string recieved from OpenSubtitles
var path = 'foo/bar.srt';                         // path to future subtitle file
var buf = new Buffer(data, 'base64');             // read the base64 string
zlib.unzip(buf, function (err, buffer) {          // decompress the content
  if (err) throw err;                             // handle decompression error
  var content = buffer.toString('utf8');          // encode in utf-8
  fs.writeFile(path, content, function (err) {    // write file to path
    if (err) throw err;                           // handle writing to file error
  });
});
```

===========

Closing this as it is not a bug with the wrapper

**Closed as completed by vankasteelj** 2018-08-23 07:43 UTC
